GET http://localhost:4000/ai/test

###

POST http://localhost:4000/ai/documents
Content-Type: application/json

{
    "content": "Employees receive 20 paid vacation days every year."
}

###

POST http://localhost:4000/ai/search
Content-Type: application/json

{
    "question": "How long do I have to get my money back?"
}